version: "3.7"

services:
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_USER: ${PG_ROOT_USER}
      POSTGRES_PASSWORD: ${PG_ROOT_PASS}
      POSTGRES_DATABASE: ${PG_DB}
    ports:
      - "5432:5432"
    restart: always

  redis:
    image: redis:alpine
    ports:
        - "6379:6379"
    restart: always

